schema_version: "v1"
expected_columns: 75

dtype_schema:
  integer_cols:
    - delinq_2yrs
    - inq_last_6mths
    - open_acc
    - pub_rec
    - total_acc
    - collections_12_mths_ex_med
    - acc_now_delinq
    - policy_code
  float_cols:
    - loan_amnt
    - funded_amnt
    - int_rate
    - installment
    - annual_inc
    - dti
  category_cols:
    - grade
    - loan_status
    - application_type
  date_cols:
    - issue_d
    - earliest_cr_line